# **PROJETO ANÁLISE DOS DADOS DO COVID 19 NO ESTADO DE SÃO PAULO**

Este projeto analisa os dados dos casos de covid 19 no estado de São Paulo do período de fevereiro de 2020 a setembro de 2021.

Os dados estão disponíveis nos sites:

https://www.seade.gov.br/coronavirus/#

https://github.com/seade-R/dados-covid-sp

https://www.seade.gov.br/

## **Importação dos Dados**

### **Importação de arquivo csv**

In [ ]:
import numpy as np
import pandas as pd

In [3]:
covid_sp = pd.read_csv(
    r"E:\1. CONTROLE DE ESTUDOS GERAL\GRADE DE ESTUDO 1 SEMESTRE 2026\3. Pyhton\Back-end - Python\2. Análise de Dados\2. Curso de Análise de Dados em Python\Project\10. Database\dados_covid_sp.csv",
    sep=';',
    encoding='utf-8'
)

# encoding: codificação de caracteres, normalmente utiliza-se o iso-8859-1, utf-8, latin-1)

In [4]:
pd.options.display.float_format = '{:.2f}'.format

In [5]:
covid_sp.head(61)

,nome_munic,codigo_ibge,dia,mes,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,...,nome_drs,cod_drs,pop,pop_60,area,map_leg,map_leg_s,latitude,longitude,semana_epidem
0,Adamantina,3500105,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Marília,5,33894,7398,41199,0,8.00,"-21,6820","-51,0737",9
1,Adolfo,3500204,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São José do Rio Preto,15,3447,761,21106,0,8.00,"-21,2325","-49,6451",9
2,Aguaí,3500303,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São João da Boa Vista,14,35608,5245,47455,0,8.00,"-22,0572","-46,9735",9
3,Águas da Prata,3500402,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São João da Boa Vista,14,7797,1729,14267,0,8.00,"-21,9319","-46,7176",9
4,Águas de Lindóia,3500501,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Campinas,3,18374,3275,6013,0,8.00,"-22,4733","-46,6314",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Barão de Antonina,3505005,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Bauru,12,3383,637,15314,0,8.00,"-23,6284","-49,5634",9
57,Barbosa,3505104,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Araçatuba,7,7284,1122,20521,0,8.00,"-21,2657","-49,9518",9
58,Bariri,3505203,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Bauru,12,33993,6061,44441,0,8.00,"-22,0730","-48,7438",9
59,Barra Bonita,3505302,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Bauru,12,34914,6605,15012,0,8.00,"-22,4909","-48,5583",9
60,Barra do Chapéu,3505351,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Sorocaba,6,5530,802,40568,0,8.00,"-24,4722","-49,0238",9

In [6]:
covid_sp.shape

(374034, 26)

### **Importação de arquivo Excel**

In [7]:
!pip uninstall openpyxl

^C

In [ ]:
!pip install openpyxl

In [ ]:
import openpyxl

In [ ]:
covid_sp2 = pd.read_excel(r'E:\1. CONTROLE DE ESTUDOS GERAL\GRADE DE ESTUDO 1 SEMESTRE 2026\3. Pyhton\Back-end - Python\2. Análise de Dados\2. Curso de Análise de Dados em Python\Project\10. Database\dados_covid_sp.xlsx')

In [ ]:
covid_sp2.head()

In [ ]:
covid_sp2.shape

### **Importação através de uma url**

In [8]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [9]:
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [10]:
iris = pd.read_csv(url, names=colnames)

In [11]:
iris.head(80)

    sepal-length  sepal-width  petal-length  petal-width            Class
0           5.10         3.50          1.40         0.20      Iris-setosa
1           4.90         3.00          1.40         0.20      Iris-setosa
2           4.70         3.20          1.30         0.20      Iris-setosa
3           4.60         3.10          1.50         0.20      Iris-setosa
4           5.00         3.60          1.40         0.20      Iris-setosa
..           ...          ...           ...          ...              ...
75          6.60         3.00          4.40         1.40  Iris-versicolor
76          6.80         2.80          4.80         1.40  Iris-versicolor
77          6.70         3.00          5.00         1.70  Iris-versicolor
78          6.00         2.90          4.50         1.50  Iris-versicolor
79          5.70         2.60          3.50         1.00  Iris-versicolor

[80 rows x 5 columns]

In [12]:
type(iris)

pandas.core.frame.DataFrame

In [13]:
iris.shape

(150, 5)

In [14]:
len(iris.Class)

150

### **Datasets das bibliotecas do Python**

https://www.statsmodels.org/stable/datasets/index.html

In [17]:
import statsmodels.api as sm

ModuleNotFoundError: No module named 'statsmodels'

In [ ]:
cancer = sm.datasets.cancer.load_pandas().data
cancer.head()

In [ ]:
type(cancer)

In [ ]:
cancer.shape

https://scikit-learn.org/stable/datasets/toy_dataset.html

In [ ]:
import sklearn

In [ ]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
iris

In [ ]:
iris.data

In [ ]:
iris.target

In [ ]:
iris.target_names

## **Organização dos dados**

### **Renomeando variáveis (colunas)**

In [ ]:
covid_sp.head()

In [ ]:
covid_sp = covid_sp.rename(columns={'nome_munic': 'municipio'})

In [ ]:
covid_sp.head(3)

In [ ]:
covid_sp.rename(columns={'datahora': 'data'}, inplace=True)

In [ ]:
covid_sp.rename(columns={'map_leg': 'rotulo_mapa','map_leg_s':'codigo_mapa'},inplace=True)

In [ ]:
covid_sp.head(3)

### **Excluindo variáveis (colunas)**

In [ ]:
# Excluir por nome
covid_sp_alterado = covid_sp.drop(columns=['cod_ra'])

In [ ]:
covid_sp_alterado.head(2)

In [ ]:
dados = pd.DataFrame({'X': [18276400722111.0, 15659540238624.0]})
dados

In [ ]:
covid_sp_alterado.shape

In [ ]:
# Excluir por número
covid_sp_alterado = covid_sp_alterado.drop(covid_sp_alterado.columns[[1]],axis=1)

In [ ]:
# Excluir mais de uma variável
covid_sp_alterado.drop(columns=['rotulo_mapa','codigo_mapa','cod_drs'],inplace=True)

In [ ]:
covid_sp_alterado.head()

In [ ]:
covid_sp_alterado.drop(covid_sp_alterado.columns[[13,14,18,19]],axis=1, inplace=True)

In [ ]:
covid_sp_alterado.shape

### **Criando e alterando valores das colunas (Variáveis)**

In [ ]:
covid_sp_alterado.head(3)

In [ ]:
covid_sp_alterado['area'] = covid_sp_alterado['area']/100
# ou
# covid_sp_alterado['area'] = covid_sp_alterado.area/100

In [ ]:
# Criação de uma coluna com a densidade demográfica (hab/km2)
covid_sp_alterado['densidade'] = covid_sp_alterado['pop'] / covid_sp_alterado['area']

In [ ]:
covid_sp_alterado.shape

In [ ]:
# Criação de uma coluna com índices
lista = list(range(1,374035))
lista

In [ ]:
df = pd.DataFrame(lista,columns=['indice'])
df

In [ ]:
# Juntando dois DataFrames
covid_sp_alterado = pd.concat([covid_sp_alterado,df],axis=1)
covid_sp_alterado.head()

In [ ]:
covid_sp_alterado = covid_sp_alterado.reindex(columns=['indice'] + list(covid_sp_alterado.columns[:-1]))
covid_sp_alterado.head()

### **Contagem de Registros das Variáveis (Colunas)**

In [ ]:
covid_sp_alterado['semana_epidem'].value_counts()

In [ ]:
covid_sp_alterado['semana_epidem'].value_counts().sort_index()

In [ ]:
from collections import Counter
Counter(covid_sp_alterado.semana_epidem)

In [ ]:
covid_sp_alterado.query('obitos_novos > 50')['municipio'].value_counts()

### **Selecionar Variáveis (Colunas) por Índices**

In [ ]:
covid_sp_alterado

In [ ]:
x = covid_sp_alterado.iloc[: , 5:13]
x

In [ ]:
type(x)

In [ ]:
y = covid_sp_alterado.iloc[:,1]
y

In [ ]:
type(y)

In [ ]:
y = covid_sp_alterado.iloc[:,1].values
y

In [ ]:
lista_y = list(y.flatten())
lista_y

In [ ]:
type(lista_y)

In [ ]:
df = pd.DataFrame(lista_y,columns=['municipio'])
df

### **Excluindo, Filtrando e Substituindo Registros (Linhas)**

In [ ]:
# Excluindo linhas por índices (valores absolutos)
covid_sp_alterado2 = covid_sp_alterado.drop(covid_sp_alterado.index[[1,3]])
covid_sp_alterado2

In [ ]:
# Excluindo linhas por índices (intervalo de valores)
covid_sp_alterado2 = covid_sp_alterado2.drop(covid_sp_alterado.index[4:7])
covid_sp_alterado2

In [ ]:
# Reordenar (resetar) índices
covid_sp_alterado2 = covid_sp_alterado2.reset_index(drop=True) # drop é para excluir índice anterior
covid_sp_alterado2

In [ ]:
ignorado = covid_sp_alterado.loc[covid_sp_alterado.municipio == 'Ignorado']
ignorado

In [ ]:
ignorado.shape

In [ ]:
covid_sp_alterado = covid_sp_alterado.loc[covid_sp_alterado.municipio != 'Ignorado']
covid_sp_alterado

In [ ]:
guarulhos = covid_sp_alterado.loc[covid_sp_alterado.municipio == 'Guarulhos']
guarulhos

In [ ]:
guarulhos.drop(columns=['data','municipio'],inplace=True)
guarulhos.head()

In [ ]:
guarulhos['semana_epidem']=guarulhos['semana_epidem'].replace({9:'nove', 10: 'dez'})
guarulhos.head(10)

In [ ]:
guarulhos['semana_epidem']=guarulhos['semana_epidem'].replace([11,12,13],['onze','doze','treze'])
guarulhos.head(30)

In [ ]:
guarulhos['casos_pc'] = guarulhos['casos_pc'].apply(lambda x: x.replace(',','.'))
guarulhos

In [ ]:
guarulhos.shape

In [ ]:
# Criar coluna com datas
import datetime

In [ ]:
data = np.array('2020-02-25', dtype = np.datetime64())
data

In [ ]:
data = data + np.arange(579)
data

In [ ]:
data = pd.DataFrame(data)
data

In [ ]:
data.columns = ['data']
data.head()

In [ ]:
guarulhos2 = pd.concat([data,guarulhos],axis=1)
guarulhos2.head()

In [ ]:
# Reordenar (resetar) índices
guarulhos = guarulhos.reset_index(drop=True) # drop é para excluir índice anterior
guarulhos.head(5)

In [ ]:
guarulhos2 = pd.concat([data,guarulhos],axis=1)
guarulhos2.head()

In [ ]:
guarulhos2.shape

### **Valores Missing (NAN)**

In [ ]:
# RELAÇÃO DA QUANTIDADE
covid_sp_alterado.isnull().sum()

In [ ]:
covid_sp_alterado['casos'].isnull().sum()

In [ ]:
# RELAÇÃO DA QUANTIDADE
covid_sp.isnull().sum()

In [ ]:
# EXCLUIR TODOS OS VALORES MISSING
covid_sp2 = covid_sp.dropna()

In [ ]:
covid_sp2.isnull().sum()

In [ ]:
# SUBSTITUIR OS VALORES MISSING PELA MEDIANA
covid_sp['obitos_novos'].fillna(covid_sp['obitos_novos'].median(), inplace=True)

In [ ]:
# SUBSTITUIR OS VALORES MISSING PELA MÉDIA
covid_sp['obitos_novos'].fillna(covid_sp['obitos_novos'].mean(), inplace=True)

In [ ]:
# SUBSTITUIR OS VALORES MISSING POR QUALQUER OUTRO VALOR
covid_sp['obitos_novos'].fillna(10, inplace=True)

### **Classificação e alteração da tipagem dos atributos**

Análise dos tipos de atributos:

object: strings

int64: inteiros

float64: reais

complex: complexos

In [ ]:
covid_sp_alterado.dtypes

In [ ]:
covid_sp_alterado['casos_pc'] = covid_sp_alterado['casos_pc'].astype(float)

In [ ]:
covid_sp_alterado['casos_pc'] = covid_sp_alterado['casos_pc'].astype(float)

In [ ]:
covid_sp_alterado['casos_pc'] = covid_sp_alterado['casos_pc'].apply(lambda x: x.replace(',','.'))
covid_sp_alterado

In [ ]:
covid_sp_alterado.dtypes

In [ ]:
covid_sp_alterado['casos_mm7d'] = covid_sp_alterado['casos_mm7d'].apply(lambda x: x.replace(',','.'))

In [ ]:
covid_sp_alterado['obitos_pc'] = covid_sp_alterado['obitos_pc'].apply(lambda x: x.replace(',','.'))

In [ ]:
covid_sp_alterado['obitos_mm7d'] = covid_sp_alterado['obitos_mm7d'].apply(lambda x: x.replace(',','.'))

In [ ]:
covid_sp_alterado['letalidade'] = covid_sp_alterado['letalidade'].apply(lambda x: x.replace(',','.'))

In [ ]:
covid_sp_alterado.head()

In [ ]:
covid_sp_alterado['casos_mm7d'] = covid_sp_alterado['casos_mm7d'].astype(float)

In [ ]:
covid_sp_alterado['obitos_pc'] = covid_sp_alterado['obitos_pc'].astype(float)

In [ ]:
covid_sp_alterado['obitos_mm7d'] = covid_sp_alterado['obitos_mm7d'].astype(float)

In [ ]:
covid_sp_alterado['letalidade'] = covid_sp_alterado['letalidade'].astype(float)

In [ ]:
# Alterar todos de uma vez
covid_sp_alterado[['casos_mm7d', 'obitos_pc','obitos_mm7d','letalidade']] = covid_sp_alterado[['casos_mm7d', 'obitos_pc','obitos_mm7d','letalidade']].apply(pd.to_numeric)

In [ ]:
covid_sp_alterado.dtypes

In [ ]:
covid_sp_alterado['data'] = covid_sp_alterado['data'].astype('datetime64[D]')
# Se ocorrer erro, substitua datetime64[D] (dia), por datetime64[s] (segundos)

In [ ]:
# prompt: alterar coluna data para data sem usar datetime64[D]

covid_sp_alterado['data'] = pd.to_datetime(covid_sp_alterado['data'])

In [ ]:
covid_sp_alterado.dtypes

## **Salvando (Exportando) o Dataframe Tratado**

In [ ]:
covid_sp_alterado.to_csv('covid_sp_tratado.csv', sep=';', encoding='utf-8', index = False)